### ISSUE TITLE
How are the reports generated?

### ISSUE THREAD

**Issue by mhmd-azeez** [Shreeshrii/tesstrain-ckb#1]
Hi, thank you for creating a ckb model. I am training my own model and I was wondering how did you generate the models in https://github.com/Shreeshrii/tesstrain-ckb/tree/master/reports ?

**Comment by Shreeshrii** [comment]
OCR evaluation is done using ISRI Analytic Tools for OCR Evaluation with
UTF-8 support <https://github.com/eddieantonio/ocreval>.

**Comment by Shreeshrii** [comment]
Look at the bash scripts in the repo, the last few starting with 6,7,8,9

**Comment by mhmd-azeez** [comment]
Thank you very much, I will check them out
