### ISSUE TITLE
High error rate with Arabic finetuning

### ISSUE THREAD

**Issue by soufieneghribi** [Shreeshrii/tesstrain-ckb#3]
I spent a lot of time toying with the parameters and retraining tesseract, and I am stuck, that's why I am contacting you.

I would appreciate a help or hint, if possible. Thank you in advance.

Here is the description of the issue:

I followed the documentation . I prepared 350 one line Arabic images (xx.png) and their transcript (xx.gt.txt) and starting training with START_MODEL=ara.

make training MODEL_NAME=elda START_MODEL=ara TESSDATA=data/ara_best

![image](https://user-images.githubusercontent.com/26394060/121221674-b2bb0400-c87d-11eb-9bb7-cf7dd599abae.png)

I am getting 100% as an error rate.

![image](https://user-images.githubusercontent.com/26394060/121221695-b77fb800-c87d-11eb-896a-9f7a851fed8a.png)

Thanks again for your help,

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesstrain/blob/master/Makefile#L89

you need to set the correct language type for RtL languages.

**Comment by soufieneghribi** [comment]
Thanks, that solved a problem.

Another question: I finetuned the model on 96 images. I started from a model that I finetuned on a specific font (START_MODEL=font_model).

I got very good results on images that are similar to the training set (error rate 0.06) . But the performance of the model over other images decreased.

I trained model on images like these:
![image](https://user-images.githubusercontent.com/26394060/121925034-674c9e00-cd34-11eb-8724-785628610c14.png)

The model performed well over these images.

An example of a prediction that got worse:






![image](https://user-images.githubusercontent.com/26394060/121925411-cc07f880-cd34-11eb-8dee-bb346911cb5f.png)

Finetuned model | Font model (START_MODEL)
-- | --
عدالد | عد اله
-- | --

**Comment by Shreeshrii** [comment]
I suggest that you post in the official tesstrain repo (under the tesseract-ocr) project. That will ensure good RTL/Arabic support for all tesseract users and you may get better feedback and resolutions to your problems. 

I had done this training only as an experiment.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesstrain

**Comment by soufieneghribi** [comment]
Okay, Thank you Shreeshrii!
